name: Profiles
version: '${project.version}'
main: com.arcturusmc.profiles.Profiles
api-version: 1.18
authors: [ JoshuaK ]
description: Profile System for Spigot
website: https://arcturusmc.com
commands:
  profile:
  setbio:
  setbadge:
